apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-{{ .Values.env.environment }}
type: Opaque
{{- if eq .Values.env.environment "staging" }}
data:
  username: {{ .Values.database.staging.username | b64enc }}
  password: {{ .Values.database.staging.password | b64enc }}
{{- else if eq .Values.env.environment "prod" }}
data:
  username: {{ .Values.database.prod.username | b64enc }}
  password: {{ .Values.database.prod.password | b64enc }}
{{- end }}
